llm: ${sub|text_res}
prompts:
    - template: "agent/workers/react/tool_sys_prompt.prompt"
      role: "system"
    - template: "agent/workers/react/tool_user_prompt.prompt"
      role: "user"
tools:
    - name: Move
      request_url: "http://172.16.33.229:18080"
    # - name: GetImageSample
    #   request_url: "http://172.16.33.229:18080"
    # - name: GetSurroundingImage
    #   request_url: "http://172.16.33.229:18080"
    # - name: StartNavigation
    #   request_url: "http://172.16.33.229:18080"
    - name: Communicate
      llm: ${sub|text_res}
      request_url: "http://172.16.33.229:8080"
    # - name: TurnLeft
    #   network_interface_name: "eth0"
    # - name: TurnRight
    #   network_interface_name: "eth0"
    # - name: MoveLeft
    #   network_interface_name: "eth0"
    # - name: MoveRight
    #   network_interface_name: "eth0"
    # - name: MoveForward
    #   network_interface_name: "eth0"
    # - name: MoveBackward
    #   network_interface_name: "eth0"
